language: scala # to trigger the build on JVM worker ('language: java' works the same)
sudo: false
env:
  - ACTIVATOR_VERSION=1.3.5
addons:
  apt:
    packages:
    - curl
before_script: 
  - unset SBT_OPTS JVM_OPTS
  - curl -O https://downloads.typesafe.com/typesafe-activator/${ACTIVATOR_VERSION}/typesafe-activator-${ACTIVATOR_VERSION}-minimal.zip
  - unzip -q typesafe-activator-${ACTIVATOR_VERSION}-minimal.zip
script: activator-${ACTIVATOR_VERSION}-minimal/activator test
notifications:
  slack:
    secure: fPEfPTu9T2KIo3Oxht9z9ZQY+2WfbrDe8VJGMjbSEWe/Ukci4mzX09T1Ab/+xPyb2wMubINE+TeY7heUiu6M0qkk3V8dVuxw3pKQZPVGMG5YFi71TbT8h/Hl8L7bHXT8dqU02JjsSLfSn39eJ0ZCgbOn9EqTs5OmeOPmyG5PglrpCJRXJsllDPK6Qte3OrgpMrx6hiQWW8RbFo4qrX1kEep+jEYUPBTYVO61POABBTndTMm7HSbGKRXCkYkt/4nvUUKZjnN9Gvgj244EA4s5VVEBt+uc0kH1BoBbPIACenji5ccsbvkI59OVkRLG+fThE5TVPjEh1VtQpIlwTsAtaldLXP9tUf8wdw/g2YmnInIFPcuGw6WcXuLywABp3SxVfTl8rJtQNubvEEtE9BtJbjrDplqEVAM+00l+tUgR46QMtH+tiwMjEx+N9BcsoPB9oYId/lZD2KK2x6H7pK+XWZkBtnwjsalybbKFRQfORQIcMTPNt0U1VZmnrc9U7CTfvmX4yg1dWyrtaqzFdLquOZjXvuqLuqYKx/xWQIr/qu15ymtzFINZnIQ83Gh0na6/q81VB2KvFeg6nLPccuqjv8ntdWxTLcVQKp1XwHTc6BZJmYgGV+p5ioKwHLL5rLMxnmgqtaSFjAGgo2hQ3WRh/MIWeqn0hOx9stbFYNoRvQ4=
  email: false
